// svelte-workout-app/src/components/Workout.svelte
<script>
  import ExerciseCard from './ExerciseCard.svelte';
  import SectionWrapper from './SectionWrapper.svelte';

  export let workout;
</script>

<SectionWrapper
  id="workout"
  header="Welcome to"
  title={['The', 'DANGER', 'zone']}
>
  <div class="flex flex-col gap-4">
    {#each workout as exercise, i}
      <ExerciseCard index={i} {exercise} />
    {/each}
  </div>
</SectionWrapper>

// react-workout-app/src/components/Workout.jsx
/* eslint-disable react/prop-types */
import ExerciseCard from './ExerciseCard'
import SectionWrapper from './SectionWrapper'

export default function Workout({ workout }) {
    return (
        <SectionWrapper id='workout' header="Welcome to" title={["The", "DANGER", "zone"]}>
            <div className='flex flex-col gap-4'>
                {workout.map((exercise, i) => (
                    <ExerciseCard index={i} exercise={exercise} key={i} />
                ))}
            </div>
        </SectionWrapper>
    )
}
