// react-workout-app/src/App.jsx
import { useState } from "react";
import Generator from "./components/Generator";
import Hero from "./components/Hero";
import Workout from "./components/Workout";
import { generateWorkout } from "./utils/functions";

export default function App() {
  const [workout, setWorkout] = useState(null)
  const [poison, setPoison] = useState('individual');
  const [muscles, setMuscles] = useState([]);
  const [goal, setGoal] = useState('strength_power');

  function updateWorkout() {
    if (muscles.length > 0) {
      const newWorkout = generateWorkout({ poison, muscles, goal });
      setWorkout(newWorkout);

      window.location.href = '#workout'
    }
  }

  return <main className="min-h-screen flex flex-col bg-gradient-to-r
  from-slate-800 to-slate-950 text-white text-sm sm:text-base">
    <Hero />
    <Generator
      poison={poison} setPoison={setPoison}
      muscles={muscles} setMuscles={setMuscles}
      goals={goal} setGoals={setGoal}
      updateWorkout={updateWorkout} />
    {!!workout && <Workout workout={workout} />}
  </main>
}

// svelte-workout-app/src/App.svelte
<script>
  import { generateWorkout } from './utils/functions';
  import Hero from './components/Hero.svelte';
  import Workout from './components/Workout.svelte';
  import Generator from './components/Generator.svelte';

  let workout = null;
  let poison = 'individual';
  let muscles = [];
  let goal = 'strength_power';

  function updateWorkout() {
    if (muscles.length > 0) {
      const newWorkout = generateWorkout({ poison, muscles, goal });
      workout = newWorkout;
      window.location.href = '#workout';
    }

    console.log(muscles);
  }
</script>

<main
  class="min-h-screen flex flex-col bg-gradient-to-r from-slate-800 to-slate-950 text-white text-sm sm:text-base"
>
  <Hero />
  <Generator {poison} {muscles} goals={goal} {updateWorkout} />
  {#if workout}
    <Workout {workout} />
  {/if}
</main>
